version: 0.2
phases:
  install:
    commands:
      # Install kubectl
      - curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.10/2019-06-21/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - kubectl version --short --client
      # Install Iam Authenticator
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$HOME/bin:$PATH
      - aws-iam-authenticator help
      # Role Authentication
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      # Configure kubectl
      - aws eks --region ap-south-1 update-kubeconfig --name mymaincluster
      # Install helm
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      # Plugin S3 and repo add
      - helm plugin install https://github.com/hypnoglow/helm-s3.git
      - helm repo add my-helm-chart s3://my-helm-chart/charts
      - helm repo list
      - helm repo update
      - helm search repo my-nginx
      - helm search repo tomcat    
  build:
    commands:
      - helm upgrade --install nikhil00 my-helm-chart/my-nginx --version 0.1.0 --namespace helm-space
      - helm upgrade --install tomcat10 my-helm-chart/tomcat --version 0.4.1 --namespace helm-space
